### ISSUE TITLE
Option to remove scroll bar

### ISSUE THREAD

**Issue by ballo** [daichan132/Youtube-Live-Chat-Fullscreen#12]
I don't need a scoll bar to scroll, and it uses up a lot of screen space. If removed, the text should wrap to the edge of the window.

**Comment by daichan132** [comment]
Thank you for creating this issue.

I think it's a very good idea and I will add an option to remove the scrollbar in the next update.

**Comment by ballo** [comment]
Thank you!

**Comment by daichan132** [comment]
The scroll bar is now only displayed when the chat field is hovered.

When the chat field is not hovered, the scrollbar width is set to 0.

**Comment by ballo** [comment]
Hm, doesn't seem to in 2.0.3?
<img width="363" alt="Screenshot 2024-02-23 at 3 51 10 PM" src="https://github.com/daichan132/Youtube-Live-Chat-Fullscreen/assets/631311/9b2d95a1-7720-4c67-9a77-61dfd8c2cbe9">

**Comment by daichan132** [comment]
It works fine on my Mac with ver 2.03, so I have a feeling that the difference in environment is the cause. I will try to fix it.

Thank you for the report!

**Comment by ballo** [comment]
FWIW I'm using Brave on MacOS

**Comment by ballo** [comment]
It's working now. Maybe I had to relaunch the browser to reset something

**Comment by daichan132** [comment]
Thank you for your report!🙏
