### ISSUE TITLE
Stopped working a few weeks ago

### ISSUE THREAD

**Issue by ballo** [daichan132/Youtube-Live-Chat-Fullscreen#37]
**Describe the bug**
Overlay never shows

**To Reproduce**
1. Go fullscreen on any stream with a live chat
2. No step 2

**Expected behavior**
The usual overlay

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser Brave
 - Version latest

**Comment by daichan132** [comment]
Thank you for creating the issue.

I tested it on my M1 MacBook Air using the Brave browser, and it worked correctly, so it seems likely that the issue may be related to ballo's environment.

The video below shows the actual operation on my device:

https://github.com/user-attachments/assets/4c6cc557-9d56-4ee6-b07e-0896574cf59a

However, on my side, it didn’t work properly before updating Brave. After updating to the latest version, it started working fine, so updating the browser to the latest version might resolve the issue.

**Comment by ballo** [comment]
> However, on my side, it didn’t work properly before updating Brave. After updating to the latest version, it started working fine, so updating the browser to the latest version might resolve the issue.

I'll try this and report back. I've also been having issues with the cursor not going away in full screen which could be related.

**Comment by ballo** [comment]
Updating the browser didn't solve the issue, but disabling all my extensions except this one did. I'm trying to figure out the conflict...

**Comment by daichan132** [comment]
I fixed the issue where the extension didn’t work properly when used alongside 'Improve YouTube!'. Updating the extension to the latest version(2.0.25) should resolve the problem.

**Comment by ballo** [comment]
Sweet! Thanks!
FYI your extension was more important to me, but now I can enable both 😊
