### ISSUE TITLE
Add to Mozilla add-on repository (sign the extension)

### ISSUE THREAD

**Issue by zwamdurkel** [daichan132/Youtube-Live-Chat-Fullscreen#38]
I've tried compiling and using the Firefox extension and it works great for me. I really love the features and the fact that it works with HyperChat as well. (would be nice if transparency would work with HyperChat. I got it to work by changing HyperChat's CSS manually.)

The only issue is that I can only add it as a temporary extension in Firefox Stable, because the extension is not signed. So please have your extension be signed by Mozilla and publish it to the add-on store.

Alternative solution: you can add unsigned add-ons to Firefox Developer Edition, but I'd rather not.

**Comment by daichan132** [comment]
I apologize for the delay, but I have now released YouTube Live Chat Fullscreen for Firefox as well.

https://addons.mozilla.org/ja/firefox/addon/youtube-live-chat-fullscreen/
