### ISSUE TITLE
Chat Toggle button is not centered in FireFox

### ISSUE THREAD

**Issue by zwamdurkel** [daichan132/Youtube-Live-Chat-Fullscreen#48]
**Describe the bug**
As you can see in the picture, the chat button is offset to the bottom on FireFox. 

**To Reproduce**
1. Install fresh firefox
2. Install the extension
3. Enter fullscreen
4. Observe that the button is offset

**Expected behavior**
The button should be centered like in chrome.

**Screenshots**
Firefox
![image](https://github.com/user-attachments/assets/a91bc07d-6ebe-4248-b9a2-6955583d823a)

Chrome
![image](https://github.com/user-attachments/assets/459090d1-cbad-4f93-90e2-ffb0a6dfb546)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: FireFox 133.0.3 (64-bit)
 - Version: 2.1.3
 
 **Unrelated**
 Thanks a ton for publishing to FireFox! I really appreciate it.

**Comment by daichan132** [comment]
Thank you for making the issue!
The fix is complete and I think it will work correctly if you update your extension version to the latest version.

**Comment by zwamdurkel** [comment]
> Thank you for making the issue! The fix is complete and it will work correctly if you update your extension version to the latest version.

Thank you for fixing it, really appreciate it.
